{% set name = "tldextract" %}
{% set version = "5.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tldextract-{{ version }}.tar.gz
  sha256: d43c7284c23f5dc8a42fd0fee2abede2ff74cc622674e4cb07f514ab3330c338

build:
  entry_points:
    - tldextract = tldextract.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - idna
    - requests >=2.1.0
    - requests-file >=1.4
    - filelock >=3.0.8

test:
  imports:
    - tldextract
  commands:
    - pip check
    - tldextract --help
  requires:
    - pip

about:
  home: https://github.com/john-kurkowski/tldextract
  summary: Accurately separates a URL's subdomain, domain, and public suffix, using the Public Suffix List (PSL). By default, this includes the public ICANN TLDs and their exceptions. You can optionally support the Public Suffix List's private domains as well.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
