{% set name = "tldextract" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac1c5daa02616e9c2608f5fb6dd93049db03d0cf46c7f6fad46e2850a984f019

build:
  noarch: python
  entry_points:
    - tldextract = tldextract.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - setuptools
    - idna
    - requests >=2.1.0
    - requests-file >=1.4
    - filelock

test:
  imports:
    - tldextract

  commands:
    - tldextract --help
    - pip check

  requires:
    - pip

about:
  home: https://github.com/john-kurkowski/tldextract
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Accurately separate the TLD from the registered domain andsubdomains of a URL, using the Public Suffix List.
  dev_url: https://github.com/john-kurkowski/tldextract

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
